name: Build app

on:
  push:
    branches: [ "**" ]
    tags: [ "v*.*.*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-app:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: heatboard
      build-target: runner
    secrets: inherit

  build-migrator:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: heatboard-migrator
      build-target: migrator
    secrets: inherit